### ISSUE TITLE
Convetration error

### ISSUE THREAD

**Issue by gavr123456789** [hbmartin/graphviz2drawio#28]
This is beta software, please report issues to:
https://github.com/hbmartin/graphviz2drawio/issues
```
Something went wrong, please report
Traceback (most recent call last):
  File "/usr/bin/graphviz2drawio", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/graphviz2drawio/__main__.py", line 26, in main
    output = convert(args.to_convert, args.program)
  File "/usr/lib/python3.7/site-packages/graphviz2drawio/graphviz2drawio.py", line 27, in convert
    [e.enrich_from_graph(graph_edges[e.gid]) for e in edges]
  File "/usr/lib/python3.7/site-packages/graphviz2drawio/graphviz2drawio.py", line 27, in <listcomp>
    [e.enrich_from_graph(graph_edges[e.gid]) for e in edges]
KeyError: 'node0:f0->node1:f0'
Sentry is attempting to send 2 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

when tried to convert that: https://graphviz.gitlab.io/_pages/Gallery/directed/datastruct.html

**Comment by hbmartin** [comment]
This is fixed in the upcoming 0.3 release and automated testing has been added for that file.
Feel free to reopen or create a new issue if that release does not work as you expect.
Thanks for the report!
